### ISSUE TITLE
Resources for helping users

### ISSUE THREAD

**Issue by dbrunson** [CampusChampions/champion_playbook#1]
If you have links to things to help champions help users, please post them here for incorporation into the site.

**Comment by dbrunson** [comment]
From Harry Mangalam: 

This document is for (non-Computer Science) graduate students who are using Linux to do large scale data analysis on Linux systems, but who have little-to-no experience in computer programming. However, these students often need to know how programs work in order to install programs writ by others, to fix common installation or run-time problems, to bypass root requirements on large systems, to accelerate their own analysis without compromising the security of the larger system.
 
You would not be reading this document as a first-time Linux user, but as a Linux user who had some experience using programs and is now trying to fix or install a recalcitrant program, whether it be a Perl or C++ program.
 
As such, you need to have a crude understanding of a Linux system, the permission system, the difference between a normal user and root, and what programs are expected to do.
 
Hence this is a meta-document about programming, not about How to Program (there’s almost nothing about programming in it) but about how programs are built and work on Linux systems and how to fix common problems associated with running them.
 
It's here: 
http://moo.nac.uci.edu/~hjm/How_Programs_Work_On_Linux.html 
 
and the asciidoc src is currently here:
http://moo.nac.uci.edu/~hjm/How_Programs_Work_On_Linux.txt
 
It will be githubbed shortly.
 
A follow-up on how to install programs on Linux is underway, but I'd be happy to have comments and critique. At any rate, feel free to use/re-use/mashup, share, etc.

**Comment by sgowtham** [comment]
Good morning.

The Linux Training Camp at Michigan Tech is a free Canvas course.

https://mtu.instructure.com/courses/1147020

Since Canvas is sync'd with our Banner system (for a vast majority of paid courses), it's not open enrollment and quizzes (i.e., training camps) are not publicly accessible. However, the rationale, syllabus,  etc. are.

I'd be more than happy to dump the contents _as is_ so that other interested institutions can tweak it to fit their needs.
